import { Bitmap, hex } from './bitmap'

/*
 * Interface icons, drawn on a 12x12 grid like the rest of the art. 'K' is the icon colour; the
 * interface picks the colour (dark on light buttons, light on dark ones).
 */

const ICONS = {
  play: [
    '............',
    '..KK........',
    '..KKKK......',
    '..KKKKKK....',
    '..KKKKKKKK..',
    '..KKKKKKKKK.',
    '..KKKKKKKKK.',
    '..KKKKKKKK..',
    '..KKKKKK....',
    '..KKKK......',
    '..KK........',
    '............',
  ],
  pause: [
    '............',
    '............',
    '..KKK..KKK..',
    '..KKK..KKK..',
    '..KKK..KKK..',
    '..KKK..KKK..',
    '..KKK..KKK..',
    '..KKK..KKK..',
    '..KKK..KKK..',
    '..KKK..KKK..',
    '............',
    '............',
  ],
  menu: [
    '............',
    '............',
    '.KKKKKKKKKK.',
    '.KKKKKKKKKK.',
    '............',
    '.KKKKKKKKKK.',
    '.KKKKKKKKKK.',
    '............',
    '.KKKKKKKKKK.',
    '.KKKKKKKKKK.',
    '............',
    '............',
  ],
  build: [
    '.........KK.',
    '........KKKK',
    '.......K.KKK',
    '......KKK.K.',
    '.....KKKKK..',
    '....KKKKK...',
    '...KKKKK....',
    '..KKKKK.....',
    '.K.KKK......',
    '.K..K.......',
    '.KKK........',
    '............',
  ],
  undo: [
    '............',
    '...K........',
    '..KK........',
    '.KKKKKKKK...',
    'KKKKKKKKKK..',
    '.KKK....KKK.',
    '..KK.....KK.',
    '...K.....KK.',
    '.........KK.',
    '........KKK.',
    '....KKKKKK..',
    '....KKKKK...',
  ],
  eraser: [
    '............',
    '............',
    '............',
    '..KKKKKKKKK.',
    '.K.....KKKKK',
    '.K.....KKKKK',
    '.K.....KKKKK',
    '..KKKKKKKKK.',
    '............',
    'KKKKKKKKKKKK',
    '............',
    '............',
  ],
  flip: [
    '............',
    '............',
    '............',
    '...K....K...',
    '..KK....KK..',
    '.KKKKKKKKKK.',
    'KKKKKKKKKKKK',
    '.KKKKKKKKKK.',
    '..KK....KK..',
    '...K....K...',
    '............',
    '............',
  ],
  sound: [
    '............',
    '.....K......',
    '....KK..K...',
    '...KKK...K..',
    'KKKKKK.K..K.',
    'KKKKKK..K.K.',
    'KKKKKK..K.K.',
    'KKKKKK.K..K.',
    '...KKK...K..',
    '....KK..K...',
    '.....K......',
    '............',
  ],
  soundOff: [
    '............',
    '.....K......',
    '....KK......',
    '...KKK......',
    'KKKKKK.K...K',
    'KKKKKK..K.K.',
    'KKKKKK...K..',
    'KKKKKK..K.K.',
    '...KKK.K...K',
    '....KK......',
    '.....K......',
    '............',
  ],
  music: [
    '............',
    '.....KKKKKK.',
    '.....KKKKKK.',
    '.....K....K.',
    '.....K....K.',
    '.....K....K.',
    '.....K....K.',
    '..KKKK..KKK.',
    '.KKKKK.KKKK.',
    '.KKKKK.KKKK.',
    '..KKK...KK..',
    '............',
  ],
  share: [
    '.....KK.....',
    '....KKKK....',
    '...KKKKKK...',
    '.....KK.....',
    '.....KK.....',
    '.KK..KK..KK.',
    '.K...KK...K.',
    '.K........K.',
    '.K........K.',
    '.K........K.',
    '.KKKKKKKKKK.',
    '............',
  ],
  people: [
    '............',
    '..KK....KK..',
    '.KKKK..KKKK.',
    '.KKKK..KKKK.',
    '..KK....KK..',
    '............',
    '.KKKK..KKKK.',
    'KKKKKKKKKKKK',
    'KKKKKKKKKKKK',
    'KKKKKKKKKKKK',
    '............',
    '............',
  ],
  restart: [
    '............',
    '....KKKK.KK.',
    '..KKKKKKKKK.',
    '.KKK....KKK.',
    '.KK....KKKK.',
    'KK..........',
    'KK..........',
    'KK........KK',
    '.KK......KK.',
    '.KKK....KKK.',
    '..KKKKKKKK..',
    '....KKKK....',
  ],
  home: [
    '.....KK.....',
    '....KKKK....',
    '...KKKKKK...',
    '..KKKKKKKK..',
    '.KKKKKKKKKK.',
    'KKKKKKKKKKKK',
    '.KK......KK.',
    '.KK.KKKK.KK.',
    '.KK.K..K.KK.',
    '.KK.K..K.KK.',
    '.KKKK..KKKK.',
    '............',
  ],
  close: [
    '............',
    '.KK......KK.',
    '.KKK....KKK.',
    '..KKK..KKK..',
    '...KKKKKK...',
    '....KKKK....',
    '....KKKK....',
    '...KKKKKK...',
    '..KKK..KKK..',
    '.KKK....KKK.',
    '.KK......KK.',
    '............',
  ],
  back: [
    '............',
    '....K.......',
    '...KK.......',
    '..KKK.......',
    '.KKKKKKKKKK.',
    'KKKKKKKKKKK.',
    '.KKKKKKKKKK.',
    '..KKK.......',
    '...KK.......',
    '....K.......',
    '............',
    '............',
  ],
  check: [
    '............',
    '..........KK',
    '.........KKK',
    '........KKK.',
    '.......KKK..',
    'KK....KKK...',
    'KKK..KKK....',
    '.KKKKKK.....',
    '..KKKK......',
    '...KK.......',
    '............',
    '............',
  ],
  lock: [
    '............',
    '....KKKK....',
    '...KK..KK...',
    '...K....K...',
    '...K....K...',
    '.KKKKKKKKKK.',
    '.KKKKKKKKKK.',
    '.KKKK..KKKK.',
    '.KKKK..KKKK.',
    '.KKKKKKKKKK.',
    '.KKKKKKKKKK.',
    '............',
  ],
  crown: [
    '............',
    '............',
    'K....KK....K',
    'KK..KKKK..KK',
    'KKK.KKKK.KKK',
    'KKKKKKKKKKKK',
    'KKKKKKKKKKKK',
    'KKKKKKKKKKKK',
    '............',
    'KKKKKKKKKKKK',
    '............',
    '............',
  ],
  pad: [
    '............',
    '............',
    '..KKKKKKKK..',
    '.KKKKKKKKKK.',
    'KK.KKKKKK.KK',
    'K...KKKK.K.K',
    'KK.KKKKKK.KK',
    'KKKKKKKKKKKK',
    'KKKK....KKKK',
    '.KK......KK.',
    '............',
    '............',
  ],
  sliders: [
    '............',
    '..KK........',
    'KKKKKKKKKKKK',
    '..KK........',
    '............',
    '........KK..',
    'KKKKKKKKKKKK',
    '........KK..',
    '............',
    '....KK......',
    'KKKKKKKKKKKK',
    '....KK......',
  ],
  trash: [
    '....KKKK....',
    'KKKKKKKKKKKK',
    'KKKKKKKKKKKK',
    '............',
    '.KKKKKKKKKK.',
    '.KK.KK.KK.K.',
    '.KK.KK.KK.K.',
    '.KK.KK.KK.K.',
    '.KK.KK.KK.K.',
    '.KK.KK.KK.K.',
    '..KKKKKKKK..',
    '............',
  ],
  plus: [
    '............',
    '............',
    '.....KK.....',
    '.....KK.....',
    '.....KK.....',
    '..KKKKKKKK..',
    '..KKKKKKKK..',
    '.....KK.....',
    '.....KK.....',
    '.....KK.....',
    '............',
    '............',
  ],
  save: [
    '............',
    '.KKKKKKKKK..',
    '.KK.....KKK.',
    '.KK.....KKKK',
    '.KK.....KKKK',
    '.KKKKKKKKKKK',
    '.KKKKKKKKKKK',
    '.KKK.....KKK',
    '.KKK.....KKK',
    '.KKK.....KKK',
    '.KKKKKKKKKKK',
    '............',
  ],
  flag: [
    '............',
    '.KK.........',
    '.KKKKKKK....',
    '.KKKKKKKKKK.',
    '.KKKKKKKKK..',
    '.KKKKKKK....',
    '.KK.........',
    '.KK.........',
    '.KK.........',
    '.KK.........',
    'KKKK........',
    '............',
  ],
} satisfies Record<string, string[]>

export type IconName = keyof typeof ICONS | 'redo' | 'musicOff'

export const ICON_NAMES = [...Object.keys(ICONS), 'redo', 'musicOff'] as IconName[]

/** One icon as a bitmap in the given colour. */
export function iconBitmap(name: IconName, color: string): Bitmap {
  const c = hex(color)
  if (name === 'redo') return iconBitmap('undo', color).flipped()
  if (name === 'musicOff') {
    // The note with a line through it.
    const b = iconBitmap('music', color)
    for (let i = 0; i < 12; i++) {
      clear(b, i + 1, i)
      b.set(i, i, c)
    }
    return b
  }
  const rows = ICONS[name]
  const b = new Bitmap(12, 12)
  for (let y = 0; y < 12; y++) for (let x = 0; x < 12; x++) if (rows[y][x] === 'K') b.set(x, y, c)
  return b
}

function clear(b: Bitmap, x: number, y: number) {
  if (x < 0 || y < 0 || x >= b.w || y >= b.h) return
  const i = (y * b.w + x) * 4
  b.data[i + 3] = 0
}
