import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { BRICK_STUDIO_MAX_BRICKS, BRICK_PART_MAP, parseBrickStudioDocument } from '@brick-studio/core'

/**
 * The committed performance fixtures (scripts/perf/fixtures, generated by
 * scripts/perf/generate-fixture.ts) must stay importable through the studio's real
 * parser as the validator evolves; docs/PERF-BASELINE.md depends on their exact sizes.
 */
const FIXTURES = [
  ['dense', 250], ['dense', 500], ['dense', 1000],
  ['mixed', 250], ['mixed', 500], ['mixed', 1000],
] as const

function loadFixture(layout: string, size: number) {
  const result = parseBrickStudioDocument(readFileSync(`scripts/perf/fixtures/${layout}-${size}.brickstudio.json`, 'utf8'))
  if (!result.ok) throw new Error(`${layout}-${size}: ${result.error.code} ${result.error.message}`)
  return result.document
}

describe('performance fixtures', () => {
  it.each(FIXTURES)('%s-%i validates with exactly that many bricks', (layout, size) => {
    const document = loadFixture(layout, size)
    expect(size).toBeLessThanOrEqual(BRICK_STUDIO_MAX_BRICKS)
    expect(document.bricks).toHaveLength(size)
    expect(document.customParts).toEqual([])
    expect(document.environmentId).toBe('classic')
  })

  it('dense fixtures are three stacked layers of one brick', () => {
    for (const size of [250, 500, 1000]) {
      const document = loadFixture('dense', size)
      expect(new Set(document.bricks.map((brick) => brick.partId))).toEqual(new Set(['brick_2x4']))
      expect([...new Set(document.bricks.map((brick) => brick.y))].sort((a, b) => a - b)).toEqual([0, 3, 6])
    }
  })

  it('mixed fixtures cover plates, slopes, round bricks and tall stacks', () => {
    for (const size of [250, 500, 1000]) {
      const document = loadFixture('mixed', size)
      const kinds = new Set(document.bricks.map((brick) => BRICK_PART_MAP[brick.partId].kind))
      expect([...kinds]).toEqual(expect.arrayContaining(['plate', 'brick', 'slope', 'round', 'cone', 'stair']))
      expect(new Set(document.bricks.map((brick) => brick.partId)).size).toBeGreaterThanOrEqual(12)
      const tallest = Math.max(...document.bricks.map((brick) => brick.y + BRICK_PART_MAP[brick.partId].height))
      expect(tallest).toBeGreaterThanOrEqual(15) // at least a five-brick tower
    }
  })
})
