/** Turns two metric sets into the FEEL.md comparison and works out what `feel.ts` says each old-engine number should be. */
import { SUB } from '@brick-studio/platformer-core/engine/constants'
import { DEFAULT_FEEL, P_SEGMENTS, feelToSub, type Feel } from '@brick-studio/platformer-core/engine/feel'
import { FRAME_MS, METRICS, compare, toleranceText, type MetricRow, type MetricSet } from './metrics'

// ---------------------------------------------------------------------------------------------- expected from feel.ts

/** One jump in sub-pixels, stepped like `stepPlayer`: gravity first (hold gravity while rising with jump held), then move. Returns apex px and steps until back on the floor line. */
export function simulateJump(speedUp: number, holdGravity: number, fallGravity: number, maxFall: number, heldFrames: number) {
  let y = 0
  let vy = -speedUp
  let apex = 0
  let steps = 0
  let rose = false
  for (;;) {
    steps++
    if (vy < 0 && steps <= heldFrames) vy += holdGravity
    else vy += fallGravity
    if (vy > maxFall) vy = maxFall
    y -= vy
    if (y > apex) apex = y
    if (y > 0) rose = true
    if (rose && y <= 0) break
    if (steps > 10000) throw new Error('jump never landed')
  }
  return { apexPx: apex / SUB, airMs: steps * FRAME_MS }
}

/** Sub-pixel distance covered while the speed falls from `v0` by `decel` per step, moving after each decrement. */
export function slideDistance(v0: number, decel: number): number {
  let v = v0
  let d = 0
  while (v > 0) {
    v = Math.max(0, v - decel)
    d += v
  }
  return d / SUB
}

/** What `feel.ts` implies for each metric, derived by hand from `stepPlayer` (see feel.test.ts for the derivation notes). */
export function expectedFromFeel(feel: Feel = DEFAULT_FEEL): MetricSet {
  const f = feelToSub(feel)
  const px = (sub: number) => (sub / SUB) * 60
  const jump = (tier: 0 | 1 | 2 | 3, heldFrames = Infinity) => simulateJump(f.jump[tier], f.hold[tier], f.fallGravity, f.maxFall, heldFrames)
  const stand = jump(0)
  const tap = jump(0, 1) // a tap holds jump for the press frame only
  const walk = jump(1)
  const run = jump(2)
  const p = jump(3)
  // First step where speed >= runMax - 1/16 px (the run meter starts filling), then 7 segments of pFillFrames, then accelerate to pMax.
  const fullAt = Math.ceil((f.runMax - Math.round(0.0625 * SUB)) / f.runAccel)
  const toP = fullAt + (P_SEGMENTS * f.pFillFrames - 1) + Math.ceil((f.pMax - f.runMax) / f.runAccel)
  return {
    walkTop: px(f.walkMax),
    runTop: px(f.runMax),
    pTop: px(f.pMax),
    tWalkTop: Math.ceil(f.walkMax / f.walkAccel) * FRAME_MS,
    tRunTop: Math.ceil(f.runMax / f.runAccel) * FRAME_MS,
    tPTop: toP * FRAME_MS,
    stopWalk: slideDistance(f.walkMax, f.releaseDecel),
    stopRun: slideDistance(f.runMax, f.releaseDecel),
    stopP: slideDistance(f.pMax, f.releaseDecel),
    skid: slideDistance(f.runMax, f.skidDecel),
    apexTap: tap.apexPx,
    apexStand: stand.apexPx,
    apexWalk: walk.apexPx,
    apexRun: run.apexPx,
    apexP: p.apexPx,
    airTap: tap.airMs,
    airStand: stand.airMs,
    airWalk: walk.airMs,
    airRun: run.airMs,
    airP: p.airMs,
    distRun: (f.runMax / SUB) * (run.airMs / FRAME_MS),
    distP: (f.pMax / SUB) * (p.airMs / FRAME_MS),
    maxFall: px(f.maxFall),
    coyote: f.coyoteFrames * FRAME_MS,
    buffer: f.bufferFrames * FRAME_MS,
    wallSlide: px(f.wallSlideMax),
    // A wall jump starts like the standing hold jump with wallJumpY and the slow hold gravity.
    wallJump: simulateJump(f.wallJumpY, f.hold[0], f.fallGravity, f.maxFall, Infinity).apexPx,
  }
}

// ---------------------------------------------------------------------------------------------- markdown

const fmt = (n: number | null, unit: string): string => {
  if (n === null) return 'n/a'
  return unit === 'px/s' ? n.toFixed(1) : unit === 'ms' ? n.toFixed(1) : n.toFixed(2)
}

export interface FeelReportInput {
  newName: string
  /** Extra lines under the title (what the new column is, how it was produced). */
  newNote: string
  old: MetricSet
  neu: MetricSet
}

export function renderFeelMarkdown(input: FeelReportInput): string {
  const rows = compare(input.old, input.neu)
  const judged = rows.filter((r) => r.pass !== null)
  const passed = judged.filter((r) => r.pass).length
  const lines: string[] = []
  lines.push('# Code Lab: Hero feel comparison (step 5)')
  lines.push('')
  lines.push('Generated by `npx vitest run src/platformer/lab/feel` (`src/platformer/lab/feel/feel.test.ts`). Do not edit by hand.')
  lines.push('')
  lines.push('- **Old**: `platformer-core` `DEFAULT_FEEL` at 60 frames/s, measured through its test harness on flat levels built in code.')
  lines.push(`- **New**: ${input.newName}. ${input.newNote}`)
  lines.push(`- **Result**: ${passed} of ${judged.length} judged metrics inside tolerance.`)
  lines.push('')
  lines.push('Same input scripts for both (per 60 Hz frame; the Code Lab runner ORs each pair of frames into one 30 tick/s tick).')
  lines.push('Positions are measured in pixels (1 Code Lab step = 1 pixel), y up. Times are in ms. Diff = new minus old.')
  lines.push('')
  let group = ''
  for (const r of rows) {
    if (r.def.group !== group) {
      if (group) lines.push('')
      group = r.def.group
      lines.push(`## ${group}`)
      lines.push('')
      lines.push('| Metric | Old | New | Diff | Tolerance | Result |')
      lines.push('| --- | ---: | ---: | ---: | --- | --- |')
    }
    lines.push(rowLine(r))
  }
  lines.push('')
  lines.push('## Known gaps (out of scope for step 5)')
  lines.push('')
  lines.push('Springs, stomps, bounce blocks and corner nudge are not measured (STEP5.md). Wall slide and wall jump are report-only, and `n/a` means the runner has no level for that scenario or the Hero never did the move.')
  lines.push('')
  return lines.join('\n')
}

function rowLine(r: MetricRow): string {
  const unit = r.def.unit
  const diff = r.diff === null ? 'n/a' : `${r.diff >= 0 ? '+' : ''}${fmt(r.diff, unit)}`
  const result = r.pass === null ? (r.def.tolerance.kind === 'report' ? 'report' : 'n/a') : r.pass ? 'pass' : 'FAIL'
  return `| ${r.def.label} (${unit}) | ${fmt(r.old, unit)} | ${fmt(r.neu, unit)} | ${diff} | ${toleranceText(r.def.tolerance, unit)} | ${result} |`
}

export { METRICS }
